### ISSUE TITLE
ExecutiveMidi中如何在一个音开始和结束分别执行一次命令?

### ISSUE THREAD

**Issue by MX-Qulin** [tremblestarman/MineAudio#1]
ExecutiveMidi中如何在一个音开始和结束分别执行一次命令?
好像 "是否在起始时刻执行" 只能选一个,能不能起始时刻和终止时刻分别执行不同的命令?

**Comment by MX-Qulin** [comment]
另:能简要说下 ```midi转换到mc命令``` 的源代码位置吗?

**Comment by tremblestarman** [comment]
- a.
    - 分别创建两个ExecutiveMidi项目，一个在起始时刻执行，一个在终止时刻执行
    - 都导出为amextension文件
    - 将两个amextension文件全部导入进a2m，导出为一个命令流或一个数据包
- b.
详见[Dll](https://github.com/tremblestarman/MineAudio/tree/master/Dll)

**Comment by MX-Qulin** [comment]
ok 谢谢~



在 2021-01-29 12:13:42，"TrembleSt" <notifications@github.com> 写道：

a.
分别创建两个ExecutiveMidi项目，一个在起始时刻执行，一个在终止时刻执行
都导出为amextension文件
将两个amextension都导入进a2m，导出为一个命令流或一个数据包
b.
详见Dll
