### ISSUE TITLE
1.16版本导出的文件无法播放

### ISSUE THREAD

**Issue by ZeroBloodedge** [tremblestarman/MineAudio#2]
- 使用软件导出midi音频，播放音频的命令方块中的命令是这样的：

execute @a ~ ~ ~ playsound minecraft:block.note_block.bell record @a ~3 ~ ~ 1 1.00000

不符合1.13以来的execute语法，于是报错无法播放。
![image](https://user-images.githubusercontent.com/64587305/102780846-9e6b7380-43d1-11eb-8419-35c05e246c02.png)

- 使用数据包方式导出，用/function music:start后显示执行了两条指令，但是没有声音。

- 初步判断是因为源代码里面“execute as”的判断只有1.13和1.14导致，请修复这个问题，非常感谢。

**Comment by tremblestarman** [comment]
https://github.com/tremblestarman/MineAudio/releases/tag/A-1.6-1
worldedit schema格式下的指令格式已修复
